# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a823ab2c1c9f5e3cd086d9bb86143b38e44a806032de09ffbb423136f39b7a7f828bdc0a9e744fac8db2ff1d58e18345d8b32a081384a93a0db7c8f253374a60

test:
  secret_key_base: 2dc0b3b442ef76fd2b0d50f698613d40d89ae6cc5eafb00da54e432c6323ad64e1852b872132bff526e5dc4def0916db8887b757c5fe8381661749223b727681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
